name: Release Obsidian Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(cat manifest.json | grep -o '"version"[^,]*' | grep -o '[0-9.]*')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"

      - name: Check if tag exists
        id: check_tag
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "::notice::Tag v${{ steps.get_version.outputs.version }} already exists. Skipping release."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "::notice::Tag v${{ steps.get_version.outputs.version }} does not exist. Proceeding with release."
          fi

      - name: Setup Node.js
        if: steps.check_tag.outputs.exists == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        if: steps.check_tag.outputs.exists == 'false'
        run: npm ci

      - name: Build plugin
        if: steps.check_tag.outputs.exists == 'false'
        run: npm run build

      - name: Create Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            main.js
            manifest.json
            styles.css
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
